version: '2'
services:
  api:
    build: ./
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB: mongodb
    ports:
      - 3000:3000
  mongodb:
    image: mongo:3.4
    ports:
      - 27017:27017

